import type { CachedRepoView } from "./repository-service"

function formatMarkdownDate(isoString: string): string {
  const date = new Date(isoString)
  return Number.isNaN(date.getTime()) ? isoString : date.toISOString().slice(0, 10)
}

export function generateBriefMarkdown(view: CachedRepoView): string {
  const lines: string[] = []

  lines.push(`# ${view.fullName}`)
  lines.push("")
  lines.push(`> Discofork repository brief — exported ${formatMarkdownDate(new Date().toISOString())}`)
  lines.push(`> Source: ${view.githubUrl}`)
  lines.push("")

  lines.push("## Summary")
  lines.push("")
  lines.push(view.upstreamSummary)
  lines.push("")

  lines.push("## Stats")
  lines.push("")
  lines.push(`| Metric | Value |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Stars | ${view.stats.stars.toLocaleString()} |`)
  lines.push(`| Forks | ${view.stats.forks.toLocaleString()} |`)
  lines.push(`| Default branch | ${view.stats.defaultBranch} |`)
  lines.push(`| Last pushed | ${view.stats.lastPushedAt} |`)
  lines.push("")

  lines.push("## Recommendations")
  lines.push("")
  lines.push(`| Category | Fork |`)
  lines.push(`|----------|------|`)
  lines.push(`| Best maintained | ${view.recommendations.bestMaintained} |`)
  lines.push(`| Closest to upstream | ${view.recommendations.closestToUpstream} |`)
  lines.push(`| Most feature-rich | ${view.recommendations.mostFeatureRich} |`)
  lines.push(`| Most opinionated | ${view.recommendations.mostOpinionated} |`)
  lines.push("")

  lines.push(`## Fork Analysis (${view.forks.length} forks)`)
  lines.push("")

  for (const fork of view.forks) {
    lines.push(`### ${fork.fullName}`)
    lines.push("")
    lines.push(`**Maintenance:** ${fork.maintenance} · **Change magnitude:** ${fork.changeMagnitude}`)
    lines.push("")
    lines.push(fork.summary)
    lines.push("")
    lines.push(`**Likely purpose:** ${fork.likelyPurpose}`)
    lines.push("")
    lines.push(`**Best for:** ${fork.bestFor}`)
    lines.push("")

    if (fork.additionalFeatures.length > 0) {
      lines.push("**Additional features:**")
      lines.push("")
      for (const feature of fork.additionalFeatures) {
        lines.push(`- ${feature}`)
      }
      lines.push("")
    }

    if (fork.missingFeatures.length > 0) {
      lines.push("**Missing features:**")
      lines.push("")
      for (const feature of fork.missingFeatures) {
        lines.push(`- ${feature}`)
      }
      lines.push("")
    }

    if (fork.strengths.length > 0) {
      lines.push("**Strengths:**")
      lines.push("")
      for (const strength of fork.strengths) {
        lines.push(`- ${strength}`)
      }
      lines.push("")
    }

    if (fork.risks.length > 0) {
      lines.push("**Risks:**")
      lines.push("")
      for (const risk of fork.risks) {
        lines.push(`- ${risk}`)
      }
      lines.push("")
    }

    lines.push("---")
    lines.push("")
  }

  lines.push(`*Generated by Discofork · ${formatMarkdownDate(new Date().toISOString())}*`)
  lines.push("")

  return lines.join("\n")
}

export function downloadBriefMarkdown(view: CachedRepoView): void {
  const markdown = generateBriefMarkdown(view)
  const filename = `${view.owner}-${view.repo}-brief.md`

  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" })
  const url = URL.createObjectURL(blob)

  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export function generateBriefJson(view: CachedRepoView): string {
  const data = {
    exportedAt: new Date().toISOString(),
    repository: view.fullName,
    source: view.githubUrl,
    cachedAt: view.cachedAt,
    summary: view.upstreamSummary,
    stats: {
      stars: view.stats.stars,
      forks: view.stats.forks,
      defaultBranch: view.stats.defaultBranch,
      lastPushedAt: view.stats.lastPushedAt,
    },
    recommendations: {
      bestMaintained: view.recommendations.bestMaintained,
      closestToUpstream: view.recommendations.closestToUpstream,
      mostFeatureRich: view.recommendations.mostFeatureRich,
      mostOpinionated: view.recommendations.mostOpinionated,
    },
    forks: view.forks.map((fork) => ({
      fullName: fork.fullName,
      maintenance: fork.maintenance,
      changeMagnitude: fork.changeMagnitude,
      summary: fork.summary,
      likelyPurpose: fork.likelyPurpose,
      bestFor: fork.bestFor,
      additionalFeatures: fork.additionalFeatures,
      missingFeatures: fork.missingFeatures,
      strengths: fork.strengths,
      risks: fork.risks,
    })),
  }

  return JSON.stringify(data, null, 2)
}

export function exportRepoBrief(view: CachedRepoView): void {
  downloadBriefMarkdown(view)
}
