import { calculateForkScore } from "./fork-score"
import {
  getForkFeatureSignalCount,
  getForkRiskSignalCount,
  getForkTopPositive,
  getForkTopRisk,
  rankForksByScore,
} from "./fork-insights"
import type { CachedForkView, CachedRepoView } from "./repository-service"

export const FORK_SHORTLIST_PROFILE_VALUES = ["all", "safe", "upside", "lowRisk", "tradeoffs"] as const

export type ForkShortlistProfile = (typeof FORK_SHORTLIST_PROFILE_VALUES)[number]

export type ForkDecisionSummary = {
  total: number
  strongCandidates: number
  reviewCandidates: number
  higherRiskCandidates: number
  bestOverall: CachedForkView | null
  lowestRisk: CachedForkView | null
  highestUpside: CachedForkView | null
}

function byScoreThenName(left: CachedForkView, right: CachedForkView): number {
  const scoreDifference = calculateForkScore(right) - calculateForkScore(left)
  return scoreDifference !== 0 ? scoreDifference : left.fullName.localeCompare(right.fullName)
}

function bySignalThenScore(
  left: CachedForkView,
  right: CachedForkView,
  signal: (fork: CachedForkView) => number,
): number {
  const signalDifference = signal(right) - signal(left)
  return signalDifference !== 0 ? signalDifference : byScoreThenName(left, right)
}

export function buildForkDecisionSummary(forks: CachedForkView[]): ForkDecisionSummary {
  const ranked = rankForksByScore(forks)
  const bestOverall = ranked[0] ?? null
  const lowestRisk =
    [...forks].sort((left, right) => {
      const riskDifference = getForkRiskSignalCount(left) - getForkRiskSignalCount(right)
      return riskDifference !== 0 ? riskDifference : byScoreThenName(left, right)
    })[0] ?? null
  const highestUpside =
    [...forks].sort((left, right) => bySignalThenScore(left, right, getForkFeatureSignalCount))[0] ?? null

  return {
    total: forks.length,
    strongCandidates: forks.filter((fork) => calculateForkScore(fork) >= 70).length,
    reviewCandidates: forks.filter((fork) => {
      const score = calculateForkScore(fork)
      return score >= 40 && score < 70
    }).length,
    higherRiskCandidates: forks.filter((fork) => calculateForkScore(fork) < 40).length,
    bestOverall,
    lowestRisk,
    highestUpside,
  }
}

export function filterForksByShortlistProfile(
  forks: CachedForkView[],
  profile: ForkShortlistProfile,
): CachedForkView[] {
  switch (profile) {
    case "safe":
      return forks.filter(
        (fork) =>
          fork.maintenance.toLowerCase() === "active" &&
          calculateForkScore(fork) >= 70 &&
          getForkRiskSignalCount(fork) <= 2,
      )
    case "upside":
      return forks.filter((fork) => getForkFeatureSignalCount(fork) >= 3 || calculateForkScore(fork) >= 75)
    case "lowRisk":
      return forks.filter((fork) => getForkRiskSignalCount(fork) <= 1 && calculateForkScore(fork) >= 60)
    case "tradeoffs":
      return forks.filter((fork) => getForkFeatureSignalCount(fork) > 0 && getForkRiskSignalCount(fork) > 0)
    default:
      return forks
  }
}

function markdownForkLine(fork: CachedForkView, index: number): string[] {
  const score = calculateForkScore(fork)
  return [
    `### ${index + 1}. ${fork.fullName} (${score}/100)`,
    "",
    `- Best for: ${fork.bestFor}`,
    `- Strongest signal: ${getForkTopPositive(fork)}`,
    `- Main caution: ${getForkTopRisk(fork)}`,
    `- Signal balance: ${getForkFeatureSignalCount(fork)} positive, ${getForkRiskSignalCount(fork)} cautions`,
    "",
  ]
}

export function generateForkShortlistMarkdown(
  view: Pick<CachedRepoView, "fullName" | "githubUrl">,
  forks: CachedForkView[],
  limit = 3,
): string {
  const ranked = rankForksByScore(forks).slice(0, limit)
  const lines = [
    `# ${view.fullName} fork shortlist`,
    "",
    `Source: ${view.githubUrl}`,
    "",
    ranked.length === 0
      ? "No forks matched the current shortlist."
      : `Top ${ranked.length} fork${ranked.length === 1 ? "" : "s"} from the current Discofork view:`,
    "",
  ]

  for (const [index, fork] of ranked.entries()) {
    lines.push(...markdownForkLine(fork, index))
  }

  lines.push("Generated by Discofork.")
  lines.push("")

  return lines.join("\n")
}
