"use client"

import { useState } from "react"
import { Check, ClipboardList } from "lucide-react"

import { buttonVariants } from "@/components/ui/button"
import type { RepoListItem, RepoListOrder, RepoListStatusFilter } from "@/lib/repository-list"
import { cn } from "@/lib/utils"

type RepoIndexSnapshotButtonProps = {
  items: RepoListItem[]
  order: RepoListOrder
  statusFilter: RepoListStatusFilter
  query: string
  language: string
  total: number
  page: number
  totalPages: number
}

function formatDate(value: string | null): string {
  if (!value) return "not available"
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? value : date.toISOString().slice(0, 10)
}

function buildSnapshotMarkdown({
  items,
  order,
  statusFilter,
  query,
  language,
  total,
  page,
  totalPages,
}: RepoIndexSnapshotButtonProps): string {
  const lines = [
    "# Discofork repository index snapshot",
    "",
    `Source: ${window.location.href}`,
    `Results: ${total.toLocaleString()} total, page ${totalPages === 0 ? 0 : page} of ${totalPages}`,
    `Filters: status=${statusFilter}, order=${order}${query ? `, query=${query}` : ""}${language ? `, language=${language}` : ""}`,
    "",
    "| Repository | Status | Forks | Stars | Last push | Cached |",
    "|---|---:|---:|---:|---|---|",
  ]

  for (const item of items.slice(0, 12)) {
    lines.push(
      `| ${item.fullName} | ${item.status} | ${item.forks?.toLocaleString() ?? "n/a"} | ${
        item.stars?.toLocaleString() ?? "n/a"
      } | ${formatDate(item.lastPushedAt)} | ${formatDate(item.cachedAt)} |`,
    )
  }

  if (items.length > 12) {
    lines.push("")
    lines.push(`Showing the first 12 repositories from ${items.length.toLocaleString()} visible rows.`)
  }

  lines.push("")
  lines.push("Generated by Discofork.")

  return lines.join("\n")
}

export function RepoIndexSnapshotButton(props: RepoIndexSnapshotButtonProps) {
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    const markdown = buildSnapshotMarkdown(props)

    try {
      await navigator.clipboard.writeText(markdown)
    } catch {
      const input = document.createElement("textarea")
      input.value = markdown
      document.body.appendChild(input)
      input.select()
      document.execCommand("copy")
      document.body.removeChild(input)
    }

    setCopied(true)
    window.setTimeout(() => setCopied(false), 2000)
  }

  return (
    <button
      type="button"
      onClick={handleCopy}
      className={cn(buttonVariants({ variant: "outline" }), "gap-2 rounded-md px-4")}
      title="Copy a Markdown snapshot of this filtered repository index"
    >
      {copied ? <Check className="h-4 w-4" /> : <ClipboardList className="h-4 w-4" />}
      {copied ? "Copied snapshot" : "Copy snapshot"}
    </button>
  )
}
